package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFC0C1FF)
val md_theme_dark_onPrimary = Color(0xFF1000A9)
val md_theme_dark_primaryContainer = Color(0xFF8083FF)
val md_theme_dark_onPrimaryContainer = Color(0xFF0D0096)
val md_theme_dark_secondary = Color(0xFFB9C8DE)
val md_theme_dark_onSecondary = Color(0xFF233143)
val md_theme_dark_secondaryContainer = Color(0xFF39485A)
val md_theme_dark_onSecondaryContainer = Color(0xFFA7B6CC)
val md_theme_dark_tertiary = Color(0xFFFFB783)
val md_theme_dark_onTertiary = Color(0xFF4F2500)
val md_theme_dark_tertiaryContainer = Color(0xFFD97721)
val md_theme_dark_onTertiaryContainer = Color(0xFF452000)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF13131B)
val md_theme_dark_onBackground = Color(0xFFE4E1ED)
val md_theme_dark_surface = Color(0xFF13131B)
val md_theme_dark_onSurface = Color(0xFFE4E1ED)
val md_theme_dark_surfaceVariant = Color(0xFF34343D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C4D7)
val md_theme_dark_outline = Color(0xFF908FA0)
val md_theme_dark_inverseOnSurface = Color(0xFF303038)
val md_theme_dark_inverseSurface = Color(0xFFE4E1ED)
val md_theme_dark_inversePrimary = Color(0xFF494BD6)
val md_theme_dark_surfaceTint = Color(0xFFC0C1FF)
val md_theme_dark_outlineVariant = Color(0xFF464554)

val light_primary = Color(0xFF4F46E5)
val premium_rose = Color(0xFFF43F5E)
val success_emerald = Color(0xFF10B981)

val surfaceContainerLowest = Color(0xFF0D0D15)
val surfaceContainerLow = Color(0xFF1B1B23)
val surfaceContainer = Color(0xFF1F1F27)
val surfaceContainerHigh = Color(0xFF292932)
val surfaceContainerHighest = Color(0xFF34343D)
